# 粉末冶金工业 = [] done
# 钢铁 = [] blank return
# 钢铁研究学报 = [] nah no update
# 钢铁研究学报_en = [] no update
# 金属功能材料 = [] done
# 连铸 = [] can't update
# 物理测试 = [] can't update
# 轧钢 = [] nah can't update'
# 中国冶金 = [] can't update
# M_M = []
# MR = []
# Tan = []