set_property IOSTANDARD LVCMOS33 [get_ports {Dout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Dout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Dout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Dout[0]}]
set_property PACKAGE_PIN U14 [get_ports {Dout[6]}]
set_property PACKAGE_PIN U15 [get_ports {Dout[5]}]
set_property PACKAGE_PIN W18 [get_ports {Dout[4]}]
set_property PACKAGE_PIN V19 [get_ports {Dout[3]}]
set_property PACKAGE_PIN U19 [get_ports {Dout[2]}]
set_property PACKAGE_PIN E19 [get_ports {Dout[1]}]
set_property PACKAGE_PIN U16 [get_ports {Dout[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports Din]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports rst]
set_property PACKAGE_PIN T17 [get_ports sys_rst]
set_property PACKAGE_PIN J1 [get_ports Din]

set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property PACKAGE_PIN J2 [get_ports a]

set_property IOSTANDARD LVCMOS33 [get_ports {Dout[7]}]
set_property PACKAGE_PIN V14 [get_ports {Dout[7]}]
